version: '3.5'

services:
  minio:
    image: passport-scanner-data-minio
    container_name: passport-scanner-data-minio
    build:
      context: ./minio
      dockerfile: ./Dockerfile
    volumes:
      - ./minio/data:/minio-data
    network_mode: host
    restart: on-failure
