version: '3.5'

networks:
  internal:
    name: passport-scanner-data

services:
  minio:
    image: psd-minio
    container_name: psd-minio
    build:
      context: ./minio
      dockerfile: ./Dockerfile
    volumes:
      - ./minio/data:/minio-data
    ports:
      - '9000:9000'
    networks:
      - internal
    restart: on-failure

  elasticmq:
    image: psd-elasticmq
    container_name: psd-elasticmq
    build:
      context: ./elasticmq
      dockerfile: ./Dockerfile
    ports:
      - '9324:9324'
    networks:
      - internal
    restart: on-failure

  project:
      image: psd-project
      container_name: psd-project
      build:
        context: ./project
        dockerfile: ./docker/dev/Dockerfile
      depends_on:
        - minio
        - elasticmq
      env_file:
        - .env
      volumes:
        - './project:/project'
      networks:
        - internal
