version: '3.5'

networks:
  internal:
    name: passport-scanner-data

services:
  minio:
    image: psd-minio
    container_name: psd-minio
    build:
      context: ./minio
      dockerfile: ./Dockerfile
    ports:
      - '9000:9000'
    restart: on-failure
    volumes:
      - '${dockerstagedir:-.}/minio/data:/minio-data'
    networks:
      - internal

  elasticmq:
    image: psd-elasticmq
    container_name: psd-elasticmq
    build:
      context: ./elasticmq
      dockerfile: ./Dockerfile
    ports:
      - '9324:9324'
    restart: on-failure
    networks:
      - internal

  processor:
    image: psd-processor
    container_name: psd-processor
    build:
      context: .
      target: base_dev
      dockerfile: ./devops/docker/Dockerfile
    depends_on:
      - minio
      - elasticmq
    env_file:
      - .env
    volumes:
      - '${dockerstagedir:-.}/src:/src'
    networks:
      - internal
