version: '3.5'

networks:
  internal:
    name: passport-scanner-data

services:
  localstack:
    image: psd-localstack
    container_name: psd-localstack
    build:
      context: ./localstack
      dockerfile: ./Dockerfile
    environment:
      - DEBUG=1
    ports:
      - '10000-10003:10000-10003'
    restart: on-failure
    networks:
      - internal

  # can't remove minio because moto3 mocks which used by localstack
  # can't mock IfMatch(ETAG precondition)
  # Maybe, just maybe, I need to create pull to their repo to fix this 'issue'
  minio:
    image: psd-minio
    container_name: psd-minio
    build:
      context: ./minio
      dockerfile: ./Dockerfile
    ports:
      - '9000:9000'
    restart: on-failure
    volumes:
      - '${dockerstagedir:-.}/minio/data:/minio-data'
    networks:
      - internal

  processor:
    image: psd-processor
    container_name: psd-processor
    build:
      context: .
      target: base_dev
      dockerfile: ./devops/docker/Dockerfile
    depends_on:
      - minio
      - localstack
    env_file:
      - .env
    volumes:
      - '${dockerstagedir:-.}/src:/src'
    networks:
      - internal
