version: '3.5'

networks:
  internal:
    name: passport-scanner-data

services:
  minio:
    image: psd-minio
    container_name: psd-minio
    build:
      context: ./minio
      dockerfile: ./Dockerfile
    volumes:
      - ./minio/data:/minio-data
    ports:
      - '9000:9000'
    networks:
      - internal
    restart: on-failure

  elasticmq:
    image: psd-elasticmq
    container_name: psd-elasticmq
    build:
      context: ./elasticmq
      dockerfile: ./Dockerfile
    ports:
      - '9324:9324'
    networks:
      - internal
    restart: on-failure

  common:
      image: psd-common
      container_name: psd-common
      build:
        context: ./project
        dockerfile: ./common/docker/dev/Dockerfile
      depends_on:
        - minio
        - elasticmq
      env_file:
        - .env
      volumes:
        - './project/common:/common'
      networks:
        - internal

  validator:
    image: psd-validator
    container_name: psd-validator
    build:
      context: ./project
      dockerfile: ./validator/docker/dev/Dockerfile
    depends_on:
      - minio
      - elasticmq
    env_file:
      - .env
    volumes:
      - './project/validator:/validator'
      - './project/common/src:/common/src'
    networks:
      - internal

  virus-scanner:
    image: psd-virus-scanner
    container_name: psd-virus-scanner
    build:
      context: ./project
      dockerfile: ./virus-scanner/docker/dev/Dockerfile
    depends_on:
      - minio
      - elasticmq
    env_file:
      - .env
    volumes:
      - './project/virus-scanner:/virus-scanner'
      - './project/common:/common'
    networks:
      - internal

  archiver:
    image: psd-archiver
    container_name: psd-archiver
    build:
      context: ./project
      dockerfile: ./archiver/docker/dev/Dockerfile
    depends_on:
      - minio
      - elasticmq
    env_file:
      - .env
    volumes:
      - './project/archiver:/archiver'
      - './project/common:/common'
    networks:
      - internal
