version: '3.5'

networks:
  internal:
    name: passport-scanner-data

services:
  minio:
    image: passport-scanner-data-minio
    container_name: passport-scanner-data-minio
    build:
      context: ./minio
      dockerfile: ./Dockerfile
    volumes:
      - ./minio/data:/minio-data
    networks:
      - internal
    restart: on-failure

  function:
    image: passport-scanner-data-function
    container_name: passport-scanner-data-function
    build:
      context: ./project
      dockerfile: ./docker/Dockerfile
    depends_on:
      - minio
    volumes:
      - './project:/project'
    networks:
      - internal
