version: '3.5'

networks:
  internal:
    name: passport-scanner-data

services:
  minio:
    image: passport-scanner-data-minio
    container_name: passport-scanner-data-minio
    build:
      context: ./minio
      dockerfile: ./Dockerfile
    volumes:
      - ./minio/data:/minio-data
    ports:
      - '9000:9000'
    networks:
      - internal
    restart: on-failure

  processor:
    image: passport-scanner-data-processor
    container_name: passport-scanner-data-processor
    build:
      context: ./project/function/processor
      dockerfile: ./docker/Dockerfile
    depends_on:
      - archiver
      - minio
    volumes:
      - './project/function/processor:/processor'
    networks:
      - internal

  archiver:
    image: passport-scanner-data-archiver
    container_name: passport-scanner-data-archiver
    build:
      context: ./project/function/archiver
      dockerfile: ./docker/Dockerfile
    depends_on:
      - minio
    volumes:
      - './project/function/archiver:/archiver'
    networks:
      - internal
