name: release

on:
  push:
    branches:
      - 'master'
    tags:
      - '[0-9]+.[0-9]+.[0-9]+'
  pull_request:

jobs:
  deploy_tests:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Create minio directories
        run: |
          mkdir --parents ./minio/data/archive
          mkdir --parents ./minio/data/quarantine
          mkdir --parents ./minio/data/unprocessed

      - name: Run Tests
        env:
          COMPOSE_FILE: "docker-compose.yml:docker-compose-ci.yml"
        run: |
          docker-compose --no-ansi up --build --remove-orphans --exit-code-from processor
      - name: Test Results
        uses: mikepenz/action-junit-report@v2
        with:
          report_paths: 'src/test-report.xml'
          fail_on_failure: true
          require_tests: true
          check_name: deploy_tests results


  package:
    needs:
      - deploy_tests
    if: ${{ github.ref == 'refs/heads/master' || startsWith(github.ref, 'refs/tags') }}
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to Github Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: docker meta details
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/${{github.repository}}
          flavor: |
            latest=auto
          tags: |
            type=semver,pattern={{version}}
            type=edge,branch=master
            type=sha

      - name: build and push container
        uses: docker/build-push-action@v2
        with:
          context: .
          file: devops/docker/Dockerfile
          push: ${{ startsWith(github.ref, 'refs/tags/') || github.ref == 'refs/heads/master' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: base_package
